version: '3'
services:
  api:
    container_name: api
    image: api
    ports:
    - "8000:8000"
    command: python3 -m uvicorn main:app --host 0.0.0.0
    restart: always
  
  api1:
    container_name: api1
    image: api
    ports:
    - "8001:8000"
    command: python3 -m uvicorn main:app --host 0.0.0.0
    restart: always